//
// Created by Ivan Yarkov on 23/07/2020.
//

#ifndef PRINCETON_ALGS4_TESTS_INCLUDE_DATA_STRUCTURES_CONVEX_HULL_TEST_H_
#define PRINCETON_ALGS4_TESTS_INCLUDE_DATA_STRUCTURES_CONVEX_HULL_TEST_H_
namespace tests {
	void runConvexHullTests();
}
#endif //PRINCETON_ALGS4_TESTS_INCLUDE_DATA_STRUCTURES_CONVEX_HULL_TEST_H_
