//
// Created by Ivan Yarkov on 07/06/2020.
//

#ifndef PRINCETON_ALGS4_TESTS_INCLUDE_DATA_STRUCTURES_QUEUE_TEST_H_
#define PRINCETON_ALGS4_TESTS_INCLUDE_DATA_STRUCTURES_QUEUE_TEST_H_

namespace tests {
	void runQueueTests();
}

#endif //PRINCETON_ALGS4_TESTS_INCLUDE_DATA_STRUCTURES_QUEUE_TEST_H_
