//
// Created by Ivan Yarkov on 16/07/2020.
//

#ifndef PRINCETON_ALGS4_TESTS_INCLUDE_DATA_STRUCTURES_SORT_TEST_H_
#define PRINCETON_ALGS4_TESTS_INCLUDE_DATA_STRUCTURES_SORT_TEST_H_
namespace tests {
	void runSortTests();
}
#endif //PRINCETON_ALGS4_TESTS_INCLUDE_DATA_STRUCTURES_SORT_TEST_H_
