//
// Created by Ivan Yarkov on 25/04/2020.
//

#ifndef PRINCETON_ALGS4_TESTS_DATA_STRUCTURES_STACK_TEST_H_
#define PRINCETON_ALGS4_TESTS_DATA_STRUCTURES_STACK_TEST_H_

namespace tests {
    void runStackTests();
}

#endif //PRINCETON_ALGS4_TESTS_DATA_STRUCTURES_STACK_TEST_H_