//
// Created by Ivan Yarkov on 26/04/2020.
//

#ifndef PRINCETON_ALGS4_TESTS_DATA_STRUCTURES_UNION_FIND_TEST_H_
#define PRINCETON_ALGS4_TESTS_DATA_STRUCTURES_UNION_FIND_TEST_H_

namespace tests {
    void runAllUnionFindTests();
}
#endif //PRINCETON_ALGS4_TESTS_DATA_STRUCTURES_UNION_FIND_TEST_H_
