//
// Created by Ivan Yarkov on 11/07/2020.
//

#ifndef PRINCETON_ALGS4_TESTS_INCLUDE_DATA_STRUCTURES_VECTOR_TEST_H_
#define PRINCETON_ALGS4_TESTS_INCLUDE_DATA_STRUCTURES_VECTOR_TEST_H_

namespace tests {
	void runVectorTests();
}
#endif //PRINCETON_ALGS4_TESTS_INCLUDE_DATA_STRUCTURES_VECTOR_TEST_H_
