//
// Created by Ivan Yarkov on 06/06/2020.
//

#ifndef PRINCETON_ALGS4_TESTS_INCLUDE_EXERCISES_PERCOLATION_TEST_H_
#define PRINCETON_ALGS4_TESTS_INCLUDE_EXERCISES_PERCOLATION_TEST_H_
namespace tests {
	void runAllPercolationTests();
}
#endif //PRINCETON_ALGS4_TESTS_INCLUDE_EXERCISES_PERCOLATION_TEST_H_
